---
- name: Converge
  hosts: all
  become: true

  tasks:
    - name: "Include staticdev.pyenv"
      ansible.builtin.include_role:
        name: "staticdev.pyenv"
      vars:
        pyenv_global:
          - 3.11.0
          - 3.10.6
        pyenv_python_versions:
          - 3.11.0
          - 3.10.6
        pyenv_virtualenvs:
          - venv_name: latest_v311
            py_version: 3.11.0
          - venv_name: latest_v310
            py_version: 3.10.6
