---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: staticdev.pyenv
      pyenv_global:
        - 3.9.6
        - 3.8.11
      pyenv_python_versions:
        - 3.9.6
        - 3.8.11
      pyenv_virtualenvs:
        - venv_name: latest_v39
          py_version: 3.9.6
        - venv_name: latest_v38
          py_version: 3.8.11
